In [4]:
# NumPy array example
import numpy as np

# Create a NumPy array with shape (2,5)
n_array = np.arange(10).reshape(2, 5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [5]:

# PyTorch tensor example
import torch

# Convert NumPy array to PyTorch tensor
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [10]:
import torch

# 텐서 생성 및 속성 확인
# # Tensor creation and property checking example
# for i in range(100000000):
    # x = torch.randn(2, 3, dtype=torch.float32, device='cpu')
#     x = x+x
#     print(f"Shape: {x.shape}, dtype: {x.dtype}, device: {x.device}")
# # Output: Shape: torch.Size([2, 3]), dtype: torch.float32, device: cpu
x = torch.randn(2, 3, dtype=torch.float32, device='cpu')
# 텐서 데이터 타입 및 장치 변환
# Convert tensor dtype and device
for i in range(100000000):
    y = x.to(dtype=torch.float16, device='cuda' if torch.cuda.is_available() else 'cpu')
    y = y+y
    # print(f"Shape: {y.shape}, dtype: {y.dtype}, device: {y.device}")

KeyboardInterrupt: 

In [11]:
import torch

# Create a 3x2 tensor filled with zeros
a = torch.zeros(3, 2)

# Create another tensor b that is a view of a with shape 2x3
b = a.view(2, 3)

# Fill tensor a with ones
a.fill_(1)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
a.fill_(3)
a


tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [15]:
b

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [16]:

# Create a new 3x2 tensor filled with zeros 
# (this doesn't affect the previous 'a')
a = torch.zeros(3, 2)

# Transpose 'a' and then reshape it to a 1D tensor with 6 elements
b = a.t().reshape(6)

# Fill tensor a with ones 
# (this will affect the newly created 'a', not the previous one)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [18]:
b

tensor([0., 0., 0., 0., 0., 0.])